#!/bin/sh
# shellcheck disable=SC1091

# This is a slightly modified version of init.sh.in from the postmarketOS initrd package:
# https://gitlab.com/postmarketOS/pmaports/blob/master/main/postmarketos-mkinitfs/init.sh.in
# I should put my changes in an initramfs hook so I can use what's upstream.

[ -e /etc/postmarketos-mkinitfs/hooks/10-verbose-initfs.sh ] && set -x

. /etc/deviceinfo
. ./init_functions.sh

export PATH=/usr/bin:/bin:/usr/sbin:/sbin
/bin/busybox --install -s
/bin/busybox-extras --install -s

# Mount everything, set up logging, modules, mdev
mount_proc_sys_dev
setup_log
setup_firmware_path
# shellcheck disable=SC2154,SC2086
[ -d /lib/modules ] && modprobe -a ${deviceinfo_modules_initfs} ext4

# FIXME - hack to wait for storage devices to appear
sleep 1
setup_mdev
mount_subpartitions
setup_framebuffer

# Hooks
for hook in /etc/postmarketos-mkinitfs/hooks/*.sh; do
	[ -e "$hook" ] || continue
	sh "$hook"
done

show_splash /splash-loading.ppm.gz

# Always run dhcp daemon/usb networking for now (later this should only
# be enabled, when having the debug-shell hook installed for debugging,
# or get activated after the initramfs is done with an OpenRC service).
setup_usb_network
start_udhcpd

mount_boot_partition
extract_initramfs_extra /boot/initramfs-postmarketos-qcom-msm8974-extra
start_charging_mode
wait_root_partition
resize_root_partition
unlock_root_partition
resize_root_filesystem
mount_root_partition

# Switch root
killall telnetd mdev msm-fb-refresher 2>/dev/null
umount /boot
umount /proc
umount /sys
umount /dev/pts
umount /dev

rm -rf /sysroot/lib/modules
cp -dpR /lib/modules /sysroot/lib
cp -dpR /copy-to-root-fs/* /sysroot
rm -f /sysroot/etc/runlevels/default/lightdm /etc/runlevels/boot/msm-fb-refresher

if [ ! -e /sysroot/etc/runlevels/boot/consolefont ] ; then
	ln -s /etc/init.d/consolefont /sysroot/etc/runlevels/boot/consolefont
fi

# shellcheck disable=SC2093
exec switch_root /sysroot /sbin/init

echo "ERROR: switch_root failed!"
echo "Looping forever. Install and use the debug-shell hook to debug this."
echo "For more information, see <https://postmarketos.org/debug-shell>"
loop_forever
